name = "discord-schedule-matching-bot"
main = "src/index.ts"
compatibility_date = "2026-01-14"

[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "development-discord-schedule-matching"
database_id = "local"

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.staging.triggers]
crons = ["*/5 * * * *"]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "staging-discord-schedule-matching"
database_id = "f8834b9c-4077-4a50-9379-e13bbaf85858"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.triggers]
crons = ["*/5 * * * *"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "production-discord-schedule-matching"
database_id = "afcd6240-cdd1-4a72-86db-116915d5e4b6"
