name = "discord-schedule-matching-bot"
main = "src/index.ts"
compatibility_date = "2026-01-14"

[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.d1_databases]]
binding = "developmentDB"
database_name = "development-discord-schedule-matching"
database_id = "local"

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[env.staging.d1_databases]]
binding = "stagingDB"
database_name = "staging-discord-schedule-matching"
database_id = "779a3b1a-8776-4296-8155-ead436888ce3"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "productionDB"
database_name = "production-discord-schedule-matching"
database_id = "afcd6240-cdd1-4a72-86db-116915d5e4b6"
