name = "discord-schedule-matching-bot"
main = "src/index.ts"
compatibility_date = "2026-01-14"

[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "development-db"
database_id = "local"

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "staging-db"
database_id = "<STAGING_DATABASE_ID>"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "production-db"
database_id = "<PRODUCTION_DATABASE_ID>"
